name: shop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-85.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^5.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
fonts:
  - family: Lato
    fonts:
    - asset: assets\fonts\Lato-Regular.ttf
    - asset: assets\fonts\Lato-Bold.ttf
      weight: 700
  - family: Lato
    fonts:
    - asset: assets\fonts\Anton-Regular.ttf
      weight: 700